# Generated by Django 2.0.5 on 2018-05-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0002_auto_20180528_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='door_controller',
            name='locality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
