# Generated by Django 2.0.5 on 2018-05-28 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0006_garage_user_registered_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door_controller',
            name='controller_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='GarageControllerApp.Controller_Type'),
        ),
    ]
