# Generated by Django 2.0.5 on 2018-05-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0007_auto_20180528_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='door_controller',
            name='device_Online',
            field=models.BooleanField(default=False),
        ),
    ]
