# Generated by Django 2.0.5 on 2018-05-27 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller_type',
            name='device_path',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='door_controller',
            name='device_port',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='door_controller',
            name='ip_address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
