# Generated by Django 2.0.5 on 2018-05-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0002_auto_20180528_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door_controller',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='garage_user',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
