# Generated by Django 2.0.5 on 2018-05-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0002_auto_20180528_0941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='GarageUser',
        ),
    ]
