# Generated by Django 2.0.5 on 2018-05-27 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0003_auto_20180528_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='doorcontroller',
            name='controller_type',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='GarageControllerApp.ControllerType'),
            preserve_default=False,
        ),
    ]
