# Generated by Django 2.0.5 on 2018-05-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0004_auto_20180528_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garageuser',
            name='create_date',
        ),
    ]
