# Generated by Django 2.0.5 on 2018-05-27 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0005_remove_garageuser_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='garageuser',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 10, 11, 0, 788663), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='doorcontroller',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 10, 11, 0, 788163), verbose_name='date added'),
        ),
    ]
