# Generated by Django 2.0.5 on 2018-05-27 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0006_auto_20180528_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorcontroller',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 10, 12, 27, 873780), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='garageuser',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 10, 12, 27, 874280), verbose_name='date added'),
        ),
    ]
