# Generated by Django 2.0.5 on 2018-05-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0007_auto_20180528_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorcontroller',
            name='create_date',
            field=models.DateTimeField(verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='garageuser',
            name='create_date',
            field=models.DateTimeField(verbose_name='date added'),
        ),
    ]
