# Generated by Django 2.0.5 on 2018-05-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0008_auto_20180528_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControllerType',
            new_name='Controller_Type',
        ),
        migrations.RenameModel(
            old_name='DoorController',
            new_name='Door_Controller',
        ),
        migrations.RenameModel(
            old_name='GarageUser',
            new_name='Garage_User',
        ),
    ]
