# Generated by Django 2.0.5 on 2018-05-27 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailAddress',
            new_name='email_address',
        ),
        migrations.AddField(
            model_name='doorcontroller',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
    ]
