# Generated by Django 2.0.5 on 2018-05-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0004_garage_user_registered_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage_user',
            name='registered_devices',
        ),
    ]
