# Generated by Django 2.0.5 on 2018-05-28 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0005_remove_garage_user_registered_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage_user',
            name='registered_devices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GarageControllerApp.Door_Controller'),
            preserve_default=False,
        ),
    ]
