# Generated by Django 2.0.5 on 2018-05-28 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0008_door_controller_device_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage_user',
            name='registered_devices',
        ),
        migrations.AddField(
            model_name='door_controller',
            name='device_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GarageControllerApp.Garage_User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='door_controller',
            name='controller_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GarageControllerApp.Controller_Type'),
        ),
    ]
