# Generated by Django 2.0.5 on 2018-05-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0009_auto_20180528_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door_controller',
            name='device_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GarageControllerApp.Garage_User'),
        ),
    ]
