# Generated by Django 2.0.5 on 2018-05-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0010_auto_20180528_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door_controller',
            name='device_Online',
            field=models.IntegerField(default=False),
        ),
    ]
