# Generated by Django 2.0.5 on 2018-05-28 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0011_auto_20180528_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door_controller',
            name='device_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Garage_User',
        ),
    ]
