# Generated by Django 2.0.5 on 2018-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageControllerApp', '0012_auto_20180528_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door_controller',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
